trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: .\scripts\bootstrap-windows.bat
    displayName: Bootstrapping
  - script: cmake --build "build\windows" --config RelWithDebInfo
    displayName: Build Release
  - script: cmake --build "build\windows" --config Debug
    displayName: Build Debug
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: bash ./scripts/bootstrap-ubuntu.sh
    displayName: Bootstrapping
  - bash: /usr/bin/cmake --build "build/ubuntu/RelWithDebInfo"
    displayName: Build Release
  - bash: /usr/bin/cmake --build "build/ubuntu/Debug"
    displayName: Build Debug
