trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: .\scripts\bootstrap-windows.bat
    displayName: Bootstrapping
  - script: cmake --build "build\windows" --config RelWithDebInfo --parallel
    displayName: Build Release
  - script: cmake --build "build\windows" --config Debug --parallel
    displayName: Build Debug
  - script: ctest --build "build\windows" --config RelWithDebInfo -R grimm
    displayName: Run Tests

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: bash ./scripts/bootstrap-ubuntu.sh
    displayName: Bootstrapping
  - bash: /usr/bin/cmake --build "build/ubuntu/RelWithDebInfo" --parallel
    displayName: Build Release
  - bash: /usr/bin/cmake --build "build/ubuntu/Debug" --parallel
    displayName: Build Debug
  - script: /usr/bin/ctest --build "build/ubuntu/RelWithDebInfo" -R grimm
    displayName: Run Tests
