trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - documentation/
    - resources/
    - README.md
    - License.txt

pr:
  autoCancel: true
  branches:
    include:
    - master

jobs:
- template: scripts/ci/azure/templates/jobs/windows.yml
- template: scripts/ci/azure/templates/jobs/ubuntu.yml
- template: scripts/ci/azure/templates/jobs/macos.yml
- template: scripts/ci/azure/templates/jobs/doxygen.yml

