trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
      cmake --version
    displayName: Build Information
  - script: |
      mkdir build
      cd build
      cmake -A x64
    displayName: CMake Configure
  - script: cmake --build build --config RelWithDebInfo --parallel
    displayName: Build Release
  - script: cmake --build build --config Debug --parallel
    displayName: Build Debug
  - script: ctest --build build --config RelWithDebInfo -R grimm
    displayName: Run Tests

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: bash ./scripts/bootstrap-ubuntu.sh
    displayName: Bootstrapping
  - bash: /usr/bin/cmake --build "build/ubuntu/RelWithDebInfo" --parallel
    displayName: Build Release
  - bash: /usr/bin/cmake --build "build/ubuntu/Debug" --parallel
    displayName: Build Debug
  - script: /usr/bin/ctest --build "build/ubuntu/RelWithDebInfo" -R grimm
    displayName: Run Tests
