trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: RelWithDebInfo
  steps:
  - script: .\scripts\bootstrap-windows.bat
    displayName: Bootstrapping
  - script: cmake --build .\build\windows --config "$(configuration)"
    displayName: Build
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        configuration: Debug
      Release:
        configuration: RelWithDebInfo
  steps:
  - bash: bash ./scripts/bootstrap-ubuntu.sh
    displayName: Bootstrapping
  - bash: /usr/bin/cmake --build "./build/ubuntu/$(configuration)"
    displayName: Build
