jobs:
# - job: Windows
#   pool:
#     vmImage: 'vs2017-win2016'
#   strategy:
#     maxParallel: 2
#     matrix:
#       Debug:
#         configuration: Debug
#       Release:
#         configuration: RelWithDebInfo
#   steps:
#   - task: CMake@1
#     displayName: Configure CMake
#     inputs:
#       cmakeArgs: -A x64 ..
#   - task: CMake@1
#     displayName: Build
#     inputs:
#       cmakeArgs: --build . --config $(configuration)
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        configuration: Debug
      # Release:
      #   configuration: RelWithDebInfo
  steps:
  - bash: sudo add-apt-repository ppa:janisozaur/cmake-update && sudo apt-get update
    displayName: Install PPA repositories
  - bash: sudo apt-get install cmake clang-3.8
    displayName: Install build dependencies
  - bash: mkdir build && cd build && /usr/bin/cmake -DCMAKE_BUILD_TYPE:STRING=$(configuration) ..
    displayName: Configure CMake
    env:
      CXX: clang++
      CXXFLAGS: -m64
  - bash: cd build && /usr/bin/cmake --build .
    displayName: Build
