jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CMake@1
    displayName:  CMake Configure
    inputs:
      cmakeArgs: -A x64 ..
  - job: Build
    displayName: Build
    strategy:
      maxParallel: 2
      matrix:
        debug:
          configuration: debug
        release:
          configuration: release
    steps:
    - task: CMake@1
      inputs:
        cmakeArgs: --build .. --config $(configuration)
