jobs:
- job: Format

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - bash: |
      set -xe
      sudo add-apt-repository 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
      sudo apt-get update -y
      sudo apt-get install -y clang-format-8
    displayName: Installing Dependencies
  - bash: |
      set -xe
      clang-format-8 --version
      cmake --version
    displayName: Build Information
  - script: |
      python scripts/ci/clang-format-check.py --exe=clang-format-8 $(find source/ -name '*.h' -o -name '*.cpp')
    displayName: Clang Format
