name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        config: [ Debug, Release ]

    name: 'Windows (${{ matrix.config }} msvc)'
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Set Environment
        run: echo "DEPS=$Env:HOME\deps" | Out-File -FilePath "$Env:GITHUB_ENV" -Append
      - name: Install Problem Matchers
        uses: Trass3r/setup-cpp@v1
        if: matrix.config == 'Debug'
      - name: Install SDL2 SDK
        run: |
          curl -s -S -o SDL2-2.0.12-win-x64.7z -L https://github.com/potatoengine/win-sdks/releases/download/sdl2-2.0.12-x64/SDL2-2.0.12-win-x64.7z
          7z x -o"$Env:DEPS" SDL2-2.0.12-win-x64.7z 
          echo "SDL2DIR=$Env:DEPS\SDL2-2.0.12-win-x64" | Out-File -FilePath "$Env:GITHUB_ENV" -Append
      - name: Install Assimp SDK
        run: |
          curl -s -S -o assimp-5.0.1-win-x64.7z -L https://github.com/potatoengine/win-sdks/releases/download/assimp-5.0.1-x64/assimp-5.0.1-win-x64.7z
          7z x -o"$Env:DEPS" assimp-5.0.1-win-x64.7z
          echo "ASSIMPDIR=$Env:DEPS\assimp-5.0.1-win-x64" | Out-File -FilePath "$Env:GITHUB_ENV" -Append
          ls -R $Env:DEPS
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Setup VS Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
      - name: Configure
        env:
          CXX: cl.exe
          CC: cl.exe
          CXXFLAGS: /FC
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DUP_CXXFLAGS:STRING="/W3 /WX /w34295 /w34189" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DBUILD_SHARED_LIBS=YES
      - name: Build
        run: cmake --build build --parallel -- -k 0 -v
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose
      - name: Build Resources
        run: cmake --build build --target potato_convert_all
