name: Build

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  build-windows:
    strategy:
      matrix:
        config: [ Debug, Release ]

    name: 'Build Windows (${{ matrix.config }})'
    runs-on: 'windows-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          set DEPS=%HOME%\deps
          curl -o SDL2-devel-2.0.9-VC.zip -L https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
          unzip SDL2-devel-2.0.9-VC.zip -d %DEPS%
          curl -o assimp-4.1.0.zip -L https://grimmdeps.blob.core.windows.net/deps/assimp-4.1.0.zip
          unzip assimp-4.1.0.zip -d %DEPS%
          echo ::set-env name=DEPS::%DEPS%
      - name: Install Ninja
        run: |
          curl -o ninja-win.zip -L https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
          unzip ninja-win.zip -d %HOME%\bin
          echo ::add-path::%HOME%\bin
      - uses: potatoengine/ghactions/setup-vsdevenv@v2
      - name: Configure
        env:
          CXXFLAGS: /W3 /WX
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DSDL2_PATH:PATH="%DEPS%/SDL2-2.0.9" -DBUILD_SHARED_LIBS=YES -DASSIMP_ROOT_DIR:PATH="%DEPS%/assimp-4.1.0" .. || exit /b 1
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose

  build-posix:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        config: [ Debug, Release ]
        include:
          - name: Ubuntu
            os: ubuntu-latest
            cxx: clang++
          - name: macOS
            os: macos-latest
            cxx: g++-7
    
    name: 'Build ${{ matrix.name }} (${{ matrix.config }} ${{ matrix.cxx }})'
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@master
      - name: Configure
        env:
          CXXFLAGS: -Wall -Werror
        run: |
          mkdir -p build
          cd build
          cmake -DBUILD_SHARED_LIBS=OFF "-DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }}" ..
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose
