name: Check

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  clang-format:
    name: 'Clang Format'
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Apt update
        run: sudo apt-get -yq update
      - name: Install toolchain
        run: sudo apt-get -yq install clang-format-11
      - uses: actions/checkout@master
      - name: Check Format
        run: python3 ./scripts/tools/run-clang-format.py -r --clang-format-executable clang-format-11 --exclude ./external --extensions h,cpp,cc ./source
