name: CI

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  build:
    strategy:
      matrix:
        platform: [ 'windows-latest' ]
        config: [ Debug ]

    name: 'Build (${{ matrix.config }} ${{ matrix.platform }})'
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@master
      - name: Install Tools
        run: |
          choco install ninja
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }}
      - name: Build
        run: |
          cd build
          cmake --build . -j
      - name: Test
        run: |
          cd build
          ctest
