name: CI

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  build:
    strategy:
      matrix:
        platform: [ 'windows-latest' ]
        config: [ Debug ]

    name: 'Build (${{ matrix.config }} ${{ matrix.platform }})'
    runs-on: '${{ matrix.platform }}'

    steps:
      - uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          curl -o SDL2-devel-2.0.9-VC.zip -L https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
          unzip SDL2-devel-2.0.9-VC.zip -d ${HOME}/deps
          curl -o assimp-4.1.0.zip -L https://grimmdeps.blob.core.windows.net/deps/assimp-4.1.0.zip
          unzip assimp-4.1.0.zip -d ${HOME}/deps
          curl -o ninja-win.zip -L https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip
          unzip ninja-win.zip -d ${HOME}/bin
        shell: bash
      - name: Configure
        run: |
          setlocal enableextensions enabledelayedexpansion
          set VCDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          set PATH=%PATH%;%HOME%\bin
          call "%VCDIR%\VC\Auxiliary\Build\vcvarsall.bat" x64
          set CC=cl.exe
          set CXX=cl.exe
          set CXXFLAGS=/W3 /WX
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=${{ matirx.config }} -DSDL2_PATH:PATH="%HOME%/deps/SDL2-2.0.9" -DBUILD_SHARED_LIBS=YES -DASSIMP_ROOT_DIR:PATH="%HOME%/deps/assimp-4.1.0" -DFETCHCONTENT_BASE_DIR=_deps .. || exit /b 1
      - name: Build
        run: |
          cd build
          cmake --build . -j
      - name: Test
        run: |
          cd build
          ctest
