name: Doxygen

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  Doxygen:
    name: Documentation
    runs-on: 'ubuntu-latest'

    steps:
      - name: Install Doxygen
        run: sudo apt-get -yq install doxygen
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DUP_BUILD_DOCS=ON ..
      - name: Build Docs
        run: |
          cd build
          cmake --build . --target doxygen
      - name: Artifact
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: build/documentation/doxygen/html
      - name: Publish
        uses: potatoengine/ghactions/publish-to-git@master
        with:
          repository: potatoengine/potatoengine.github.io
          branch: master
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: build/documentation/doxygen/html
          target_folder: master
        if: success() ##&& github.event == 'push'
