name: Doxygen

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  Doxygen:
    name: Documentation
    runs-on: 'ubuntu-latest'

    steps:
      - name: Install Doxygen
        run: sudo apt-get -yq install doxygen
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DUP_BUILD_DOCS=ON ..
      - name: Build Docs
        run: |
          cd build
          cmake --build . --target doxygen
      - name: Artifact
        if: false
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: build/documentation/doxygen/html
      - name: Publish
        run: |
          set -o xtrace
          REPOSITORY=potatoengine/potatoengine.github.io
          BRANCH=master
          SOURCE_FOLDER=build/documentation/doxygen/html
          REPO_URL="https://${{ secrets.GH_PAT }}@github.com/${REPOSITORY}.git"
          AUTHOR="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          echo "Publishing ${SOURCE_FOLDER} to ${REPO_URL}:${BRANCH}"
          mkdir __work__ && cd __work__
          git init || exit 1
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git remote add origin "${REPO_URL}"
          git fetch --depth 1 origin master || exit 1
          git checkout -b "${BRANCH}" || exit 1
          git pull || exit 1
          rsync -a --delete --exclude=/.git "${GITHUB_WORKSPACE}/${SOURCE_FOLDER}/" . || exit 1
          git add . || exit 1
          git commit -a -m "Publish from ${GITHUB_WORKFLOW} at ${GITHUB_REPOSITORY}" --author="${AUTHOR}" || exit 1
          git status || exit 1
          git push origin "${BRANCH}"
