name: Doxygen

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  Doxygen:
    name: Documentation
    runs-on: 'ubuntu-latest'

    steps:
      - name: Install Doxygen
        run: sudo apt-get -yq install doxygen
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DUP_BUILD_DOCS=ON ..
      - name: Build Docs
        run: |
          cd build
          cmake --build . --target doxygen
      - name: Artifact
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: build/documentation/doxygen/html
      - name: Publish
        run: |
          REPOSITORY=potatoengine/potatoengine.github.io
          REMOTE_BRANCH=master
          SOURCE_FOLDER=build/documentation/doxygen/html
          REPO_URL="https://${{ secrets.GH_PAT }}@github.com/${REPOSITORY}.git"
          AUTHOR="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          REF="${GITHUB_BASE_REF:-${GITHUB_REF}}"
          REF_BRANCH=$(echo "${REF}" | rev | cut -d/ -f1 | rev)
          [ -z "$REF_BRANCH"] && echo "No ref branch" && echo 1
          echo "Publishing ${SOURCE_FOLDER} to ${REPO_URL}:${REMOTE_BRANCH}"
          mkdir __work__ && cd __work__
          git init || exit 1
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git remote add origin "${REPO_URL}"
          git fetch --depth 1 origin master || exit 1
          git checkout -b "${REMOTE_BRANCH}" || exit 1
          git pull origin "${REMOTE_BRANCH}" || exit 1
          rsync -a --delete "${GITHUB_WORKSPACE}/${SOURCE_FOLDER}/" "${REF_BRANCH}" || exit 1
          git add "${REF_BRANCH}" || exit 1
          git commit -m "Publish from ${GITHUB_WORKFLOW} at ${GITHUB_REPOSITORY}:${REF_BRANCH}" --author="${AUTHOR}" || exit 1
          git push origin "${REMOTE_BRANCH}"
        #if: success() && github.event == 'push')
