name: Doxygen

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  Doxygen:
    name: Documentation
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@master
      - name: Install Doxygen
        run: sudo apt-get -yq install doxygen
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DUP_BUILD_DOCS=ON ..
      - name: Build Docs
        run: |
          cd build
          cmake --build . --target doxygen
#      - name: Artifact
#        uses: actions/upload-artifact@master
#        with:
#          name: html-docs
#          path: build/documentation/doxygen/html
      - name: Publish
        run: |
          REPOSITORY=potatoengine/potatoengine.github.io
          BRANCH=master
          SOURCE_FOLDER=build/documentation/doxygen/html
          REPO_URL="https://${{ secrets.GH_PAT }}@github.com/${REPOSITORY}.git"
          AUTHOR="${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
          echo "Publishing ${SOURCE_FOLDER} to ${REPO_URL}:${BRANCH}"
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone --depth 1 --single-branch --no-tags --branch "${BRANCH}" "${REPO_URL}" __work__ || exit 1
          rsync -a --delete "${SOURCE_FOLDER}/" __work__ || exit 1
          cd __work__
          git add -v * || exit 1
          git commit -a -m "Publish from ${GITHUB_WORKFLOW} at ${GITHUB_REPOSITORY}" --author="${AUTHOR}" || exit 1
          git status
          echo git push --force
