name: Build

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  build-windows:
    strategy:
      matrix:
        config: [ Debug, Release ]

    name: 'Windows (${{ matrix.config }} msvc)'
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@master
      - name: Set Environment
        run: echo "::set-env name=DEPS::$Env:HOME\deps"
      - name: Install SDL2 SDK
        run: |
          curl -s -S -o SDL2-devel-2.0.9-VC.zip -L https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
          unzip SDL2-devel-2.0.9-VC.zip -d "$Env:DEPS"
          echo "::set-env name=SDL2DIR::$Env:DEPS\SDL2-2.0.9"
      - name: Install Assimp SDK
        run: |
          curl -s -S -o assimp-4.1.0.zip -L https://grimmdeps.blob.core.windows.net/deps/assimp-4.1.0.zip
          unzip assimp-4.1.0.zip -d "$Env:DEPS"
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup VS Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Configure
        env:
          CXXFLAGS: /W3 /WX
          CXX: cl.exe
          CC: cl.exe
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DBUILD_SHARED_LIBS=YES -DASSIMP_ROOT_DIR:PATH="$Env:DEPS/assimp-4.1.0" ..
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose

  build-ubuntu:
    strategy:
      matrix:
        config: [ 'Debug', 'Release' ]
        cxx: [ 'g++-10', 'clang++-10' ]
        include:
          - cxx: g++-10
            cc: gcc-10
            cxxflags: -Wall -Werror -Wno-error=maybe-uninitialized -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations
            packages: g++-10 gcc-10 libstdc++-10-dev
          - cxx: clang++-10
            cc: clang-10
            cxxflags: -Wall -Werror -Wno-unused-function -Wno-unused-variable -stdlib=libc++
            packages: clang-10 clang-tidy-10 clang-format-10 libc++-10-dev libc++abi-10-dev
            clang_tidy: clang-tidy-10
            clang_format: clang-format-10
    
    name: 'Ubuntu (${{ matrix.config }} ${{ matrix.cxx }})'
    runs-on: 'ubuntu-latest'
    container:
      image: 'ubuntu:20.04'

    steps:
      - uses: actions/checkout@master
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Apt update
        run: apt-get -yq update
      - name: Install libraries
        run: apt-get -yq install uuid-dev
      - name: Install toolchain
        run: apt-get -yq install cmake ${{ matrix.packages }}
        if: success() && matrix.packages != ''
      - name: Check Format
        run: |
          python3 .github/scripts/run-clang-format.py -r --clang-format-executable "${{ matrix.clang_format }}" --exclude ./external --extensions h,cpp,cc ./source
        if: success() && matrix.clang_format != ''
      - name: Configure
        env:
          CXXFLAGS: '${{ matrix.cxxflags }}'
          CXX: '${{ matrix.cxx }}'
          CC: '${{ matrix.cc }}'
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja -DBUILD_SHARED_LIBS=OFF "-DUP_CLANG_TIDY:PATH=${{ matrix.clang_tidy }}" "-DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }}" ..
      - name: Build
        run: cmake --build build --parallel
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose

  doxygen:
    name: Documentation
    runs-on: 'ubuntu-latest'
    container:
      image: 'ubuntu:20.04'

    steps:
      - uses: actions/checkout@master
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Apt update
        run: apt-get -yq update
      - name: Install Doxygen
        run: apt-get -yq install doxygen
      - name: Install libraries
        run: apt-get -yq install uuid-dev
      - name: Install toolchain
        run: apt-get -yq install cmake g++-10 gcc-10 libstdc++-10-dev
      - name: Configure
        env:
          CXX: 'g++-10'
          CC: 'gcc-10'
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DUP_BUILD_DOCS=ON ..
      - name: Build Docs
        run: cmake --build build --target doxygen
      - name: Post Artifacts
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: build/documentation/doxygen/html

  build-all:
    name: All
    needs: [ 'build-windows', 'build-ubuntu', 'doxygen' ]
    runs-on: 'ubuntu-latest'

    steps:
      - name: Determine Branch
        id: branch
        shell: bash
        run: 'echo ::set-output name=branch::$(echo "${GITHUB_BASE_REF:-GITHUB_REF}" | rev | cut -d/ -f1 | rev)'
      - name: Fetch Documentation Artifacts
        uses: actions/download-artifact@master
        with:
          name: html-docs
          path: html
        if: success() && github.event == 'push'
      - name: Publish to potatoengine.github.io
        uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: potatoengine/potatoengine.github.io
          branch: master
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: html
          target_folder: '${{ steps.branch.outputs.branch }}'
        if: success() && github.event == 'push'
      - run: echo "Build Complete"
