name: Build

on:
  push:
    branches:
      - master
  pull_request: []

jobs:
  build-windows:
    strategy:
      matrix:
        config: [ Debug, Release ]

    name: 'Windows (${{ matrix.config }} msvc)'
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Set Environment
        run: echo "::set-env name=DEPS::$Env:HOME\deps"
      - name: Install SDL2 SDK
        run: |
          curl -s -S -o SDL2-devel-2.0.9-VC.zip -L https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip
          unzip SDL2-devel-2.0.9-VC.zip -d "$Env:DEPS"
          echo "::set-env name=SDL2DIR::$Env:DEPS\SDL2-2.0.12"
      - name: Install Assimp SDK
        run: |
          curl -s -S -o assimp-4.1.0.zip -L https://grimmdeps.blob.core.windows.net/deps/assimp-4.1.0.zip
          unzip assimp-4.1.0.zip -d "$Env:DEPS"
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup VS Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Configure
        env:
          CXX: cl.exe
          CC: cl.exe
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DUP_CXXFLAGS:STRING="/W3 /WX" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }} -DBUILD_SHARED_LIBS=YES -DASSIMP_ROOT_DIR:PATH="$Env:DEPS/assimp-4.1.0"
      - name: Build
        run: cmake --build build --parallel -- -k 0 -v
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose
      - name: Build Resources
        run: cmake --build build --target potato_convert_all

  build-ubuntu:
    strategy:
      matrix:
        config: [ 'Debug', 'Release' ]
        cxx: [ 'g++-10', 'clang++-10' ]
        include:
          - cxx: g++-10
            cc: gcc-10
            warnings: -Wall -Werror -Wno-volatile # GLM triggers volatile
            packages: g++-10 gcc-10 libstdc++-10-dev
          - cxx: clang++-10
            cc: clang-10
            cxxflags: -stdlib=libc++
            warnings: -Wall -Werror -Wno-deprecated-volatile # GLM triggers deprecated-volatile
            packages: clang-10 libc++-10-dev libc++abi-10-dev
    
    name: 'Ubuntu (${{ matrix.config }} ${{ matrix.cxx }})'
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Apt update
        run: sudo apt-get -yq update
      - name: Install libraries
        run: sudo apt-get -yq install uuid-dev libsdl2-dev libassimp-dev
      - name: Install toolchain
        run: sudo apt-get -yq install cmake ${{ matrix.packages }}
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure
        env:
          CXXFLAGS: '${{ matrix.cxxflags }}'
          CXX: '${{ matrix.cxx }}'
          CC: '${{ matrix.cc }}'
        run: |
          mkdir -p build
          cmake -S . -B build -G Ninja -DUP_CXXFLAGS:STRING="${{ matrix.warnings }}" -DBUILD_SHARED_LIBS=OFF "-DCMAKE_BUILD_TYPE:STRING=${{ matrix.config }}" ..
      - name: Build
        run: cmake --build build --parallel -- -k 0 -v
      - name: Test
        run: |
          cd build
          ctest -T test -R potato --verbose
      - name: Build Resources
        run: cmake --build build --target potato_convert_all

  clang-format:
    name: 'Clang Format'
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Apt update
        run: sudo apt-get -yq update
      - name: Install toolchain
        run: sudo apt-get -yq install clang-format-10
      - uses: actions/checkout@master
      - name: Check Format
        run: python3 ./scripts/tools/run-clang-format.py -r --clang-format-executable clang-format-10 --exclude ./external --extensions h,cpp,cc ./source

  clang-tidy:
    name: 'Clang Tidy'
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Apt update
        run: sudo apt-get -yq update
      - name: Install libraries
        run: sudo apt-get -yq install uuid-dev libsdl2-dev libassimp-dev
      - name: Install toolchain
        run: sudo apt-get -yq install cmake clang-tidy-10 libc++-10-dev libc++abi-10-dev
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure
        env:
          CXXFLAGS: -stdlib=libc++
          CXX: clang++-10
          CC: clang-10
        run: |
          mkdir -p build
          cmake -S . -B build -G Ninja -DBUILD_SHARED_LIBS=OFF "-DUP_CLANG_TIDY:PATH=clang-tidy-10" "-DCMAKE_BUILD_TYPE:STRING=Debug"
      - name: Tidy
        run: python3 ./scripts/tools/run-clang-tidy.py --clang-tidy=clang-tidy-10 --build build/ --quiet source/ --exclude test

  doxygen:
    name: Documentation
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Apt update
        run: sudo apt-get -yq update
      - name: Install Doxygen
        run: sudo apt-get -yq install doxygen
      - name: Install libraries
        run: sudo apt-get -yq install uuid-dev libsdl2-dev libassimp-dev
      - name: Install toolchain
        run: sudo apt-get -yq install cmake g++-10 gcc-10 libstdc++-10-dev
      - uses: actions/checkout@master
        with:
          lfs: true
      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Configure
        env:
          CXX: 'g++-10'
          CC: 'gcc-10'
        run: |
          mkdir build
          cmake -S . -B build -G Ninja -DUP_BUILD_DOCS=ON
      - name: Build Docs
        run: cmake --build build --target doxygen
      - name: Post Artifacts
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: build/documentation/doxygen/html

  build-all:
    name: All
    needs: [ 'build-windows', 'build-ubuntu', 'doxygen', 'clang-format', 'clang-tidy' ]
    runs-on: 'ubuntu-latest'

    steps:
      - name: Determine Branch
        id: branch
        shell: bash
        run: 'echo ::set-output name=branch::$(echo "${GITHUB_BASE_REF:-GITHUB_REF}" | rev | cut -d/ -f1 | rev)'
      - name: Fetch Documentation Artifacts
        uses: actions/download-artifact@master
        with:
          name: html-docs
          path: html
        if: success() && github.event == 'push'
      - name: Publish to potatoengine.github.io
        uses: seanmiddleditch/gha-publish-to-git@master
        with:
          repository: potatoengine/potatoengine.github.io
          branch: master
          github_token: '${{ secrets.GITHUB_TOKEN  }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: html
          target_folder: '${{ steps.branch.outputs.branch }}'
        if: success() && github.event == 'push'
      - run: echo "Build Complete"
